<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.5 on win32)" generated="20220711 21:47:22.115" rpa="false" schemaversion="3">
<suite id="s1" name="DH" source="C:\Users\K3N3D\Desktop\WorkSpaceDesenvolvimento\Certified-Tech-Developer\testing-I\robot\DH.robot">
<test id="s1-t1" name="Validação das informações do curso de Data Analytics" line="8">
<status status="FAIL" starttime="20220711 21:47:22.837" endtime="20220711 21:47:22.840">Test contains no keywords.</status>
</test>
<test id="s1-t2" name=" Clicar em “Aceitar Cookies”" line="9">
<status status="FAIL" starttime="20220711 21:47:22.846" endtime="20220711 21:47:22.848">Test contains no keywords.</status>
</test>
<status status="FAIL" starttime="20220711 21:47:22.121" endtime="20220711 21:47:22.852"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="2" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="2" skip="0" id="s1" name="DH">DH</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220711 21:47:22.090" level="ERROR">Error in file 'C:\Users\K3N3D\Desktop\WorkSpaceDesenvolvimento\Certified-Tech-Developer\testing-I\robot\DH.robot' on line 10: Unrecognized section header '*'. Valid sections: 'Settings', 'Variables', 'Test Cases', 'Tasks', 'Keywords' and 'Comments'.</msg>
<msg timestamp="20220711 21:47:22.828" level="ERROR">Error in file 'C:\Users\K3N3D\Desktop\WorkSpaceDesenvolvimento\Certified-Tech-Developer\testing-I\robot\DH.resource' on line 18: Creating keyword 'Wait and Click' failed: Keyword with same name defined multiple times.</msg>
</errors>
</robot>
